services:
  mongo:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
 
  envio-video-api:
    build:
      context: .
      dockerfile: EnvioVideoAPI/Dockerfile
    container_name: envio_video_api
    ports:
      - "8080:8080"
    volumes:
      - videos_data:/app/videos
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

volumes:
  videos_data:
    driver: local
  mongo_data: