name: Testes em Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar pacotes
        run: dotnet restore

      - name: Compilar solução
        run: dotnet build --configuration Release

      - name: Rodar testes - ArmazenamentoVideoServiceTests
        run: dotnet test ./ArmazenamentoVideoServiceTests/ArmazenamentoVideoServiceTests.csproj --configuration Release --no-build --verbosity normal

      - name: Rodar testes - DomainTests
        run: dotnet test ./DomainTests/DomainTests.csproj --configuration Release --no-build --verbosity normal

      - name: Rodar testes - EnvioVideoApplicationTests
        run: dotnet test ./EnvioVideoApplicationTests/EnvioVideoApplicationTests.csproj --configuration Release --no-build --verbosity normal
